dependentlist/app/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('<int:pk>/', views.testsFuel, name="tests_fuel"),
   path('package/<int:pk>/', views.testsPackage, name="tests_package"),


]

dependentlist/app/urls.py
from django.urls import path
from .import views

urlpatterns = [
	path('', views.createSample, name='createsample')
]

dependentlist/dependentlist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('api/', include('app.api.urls')),
]

dependentlist/app/models.py
from django.db import models

class FuelType(models.Model):
	name = models.CharField(max_length=200, null=True)

	def __str__(self):
		return self.name

class LabTest(models.Model):
	name = models.CharField(max_length=200, null=True)
	fuels = models.ManyToManyField(FuelType,  blank=True)
	
	def __str__(self):
		return self.name

class Package(models.Model):
	name = models.CharField(max_length=200, null=True)
	tests = models.ManyToManyField(LabTest,  blank=True)
	
	def __str__(self):
		return self.name

class Sample(models.Model):
	customer = models.CharField(max_length=200, null=True)
	fuel = models.ForeignKey(FuelType, null=True, on_delete = models.CASCADE)
	package = models.ForeignKey(Package, null=True, on_delete = models.CASCADE)
	tests = models.ManyToManyField(LabTest,  blank=True)
	
	def __str__(self):
		return self.customer + ' ' + str(self.id)

dependentlist/app/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class SifForm(forms.ModelForm):
	class Meta:
		model = Sample
		fields = '__all__'
		exclude = ['tests']

dependentlist/app/api/views.py
from app.models import *
from django.http import JsonResponse
from . serializers import *

def testsFuel(request, pk):
	tests = LabTest.objects.filter(fuels=pk)
	serializer = TestSerializer(tests, many=True)
	return JsonResponse(serializer.data, safe=False)

def testsPackage(request, pk):
	package = Package.objects.get(id=pk)
	tests = package.tests
	serializer = TestSerializer(tests, many=True)
	return JsonResponse(serializer.data, safe=False)

dependentlist/app/views.py
from django.shortcuts import render
from .forms import *
from .models import *


def createSample(request):
	form = SifForm()
	context = {'form':form}
	return render(request, 'app/create_sample.html', context)

dependentlist/app/templates/app/create_sample.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<h3>Create Sample</h3>

<form>
	{% csrf_token %}
	{{form.as_p}}

	<div id="tests">
		<hr>
		<p><strong>Tests</strong></p>
	</div>

	<input type="submit">
</form>

<script>


	function addTests(tests){
		$('#tests').empty()
		for (var i = 0; i < tests.length; i++){
	        var test = `
	        <div class="test-check">
	          <input id="${tests[i].id}" class="checkbox" type="checkbox" name="tests" value="${tests[i].id}"> ${tests[i].name}<br>
	        </div>
	        `

	        $('#tests').append(test)
    	}
    	$( "#id_package" ).trigger( "change" );
	}

	function checkTests(tests, checks){
		var checksList = []
		for (var i = 0; i < checks.length; i++){

			$('#' + checks[i].id).prop('checked', false);
			checksList.push(parseInt(checks[i].value))
    	}

		for (var i = 0; i < tests.length; i++){
			
			if (checksList.includes(tests[i].id)){
				 $('#' + tests[i].id).prop('checked', true);
			}
    	}
	}

	$('#id_fuel').change(function(){
		id = this.value
		var url = 'http://127.0.0.1:8000/api/' + id + '/'

		$.ajax({
              url:url,
              success:function(tests){
             	addTests(tests)
              }
           });
	})

	$('#id_package').change(function(){
		id = this.value

		if (id){
			var url = 'http://127.0.0.1:8000/api/package/' + id + '/'
			var checks = $('.checkbox')

			$.ajax({
	              url:url,
	              success:function(tests){
	             	checkTests(tests, checks)
	              }
	           });
		}
	})
</script>